"""create_temp_codes_table

Revision ID: 527b8c2bcc8c
Revises: c6ba697a11dd
Create Date: 2025-10-12 23:28:17.908674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '527b8c2bcc8c'
down_revision: Union[str, None] = 'c6ba697a11dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temp_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('code_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['hash_clash.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='hash_clash'
    )
    op.create_index(op.f('ix_temp_codes_id'), 'temp_codes', ['id'], unique=False, schema='hash_clash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_temp_codes_id'), table_name='temp_codes', schema='hash_clash')
    op.drop_table('temp_codes', schema='hash_clash')
    # ### end Alembic commands ###
